<?php
    return [
        "GET|/"                     => GbClicker\Controller\LandingpageController::class,
        "GET|/login"                => GbClicker\Controller\Auth\LoginController::class,
        "GET|/register"             => GbClicker\Controller\Auth\RegisterController::class,
        "GET|/logout"               => GbClicker\Controller\Auth\Actions\LogoutController::class,
        "GET|/shop"                 => GbClicker\Controller\Shop\ShopController::class,
        "GET|/home"                 => GbClicker\Controller\Game\HomeController::class,
        "POST|/register/save"       => GbClicker\Controller\Auth\Actions\SaveRegisterController::class,
        "POST|/home"                => GbClicker\Controller\Game\HomeController::class,
        "POST|/home/save"           => GbClicker\Controller\Game\Actions\SaveGameController::class,
        "POST|/admin/items/save"    => GbClicker\Controller\Admin\Actions\SaveItemController::class,
        "GET|/admin/items"          => GbClicker\Controller\Admin\ItemController::class,
        "GET|/admin/accounts"       => GbClicker\Controller\Admin\AccountsController::class,
        "GET|/profile"              => GbClicker\Controller\User\ProfileController::class,
        "GET|/admin"                => GbClicker\Controller\Admin\AdminPageController::class,
        "GET|/ranking"              => GbClicker\Controller\User\RankingController::class,
        "POST|/admin/accounts/save" => GbClicker\Controller\Admin\Actions\SaveAccountEditController::class,
        "POST|/shop/purchase"       => GbClicker\Controller\Shop\Actions\SavePurchaseController::class,
        "POST|/save/money"          => GbClicker\Controller\Game\Actions\SaveMoneyController::class,
        "GET|/get/item_quant_by_id" => GbClicker\Controller\Api\GetItemQuantAPI::class,
        "GET|/get/user_info"        => GbClicker\Controller\Api\GetUserInfoAPI::class,
        "POST|/post/click_save"     => GbClicker\Controller\Game\Actions\ClickController::class,
        "POST|/post/minions_money"  => GbClicker\Controller\Game\Actions\MinionsMoneyController::class,
    ];
